### ISSUE TITLE
Inference Script

### ISSUE THREAD

**Issue by ahmedheakl** [neulab/Pangea#1]
Hello team,

Nice work! Can you please provide a short script for evaluation? I tried similar codes as LLaVa-NeXt and Qwen2-VL, but your processor returns a list of token_ids when I do `processor.apply_chat_template(prompt)`. It seems that your processor is just a `Qwen2TokenizerFast`. Can you please fix?

**Comment by xiangyue9607** [comment]
Hi, if you are using HF inference / generation. You might need to use the HF version of our checkpoint, which is available here: https://huggingface.co/neulab/Pangea-7B-hf

**Comment by yueqis** [comment]
Hi,
Thank you for your feedback! Could you provide specific code and logs you are attempting? Thanks!

**Comment by ahmedheakl** [comment]
Thank you so much for the code @xiangyue9607. It would be lovely to add a similar code to [Pangea-7B](https://huggingface.co/neulab/Pangea-7B).

Here you go @yueqis 
```
from transformers import AutoProcessor
processor = AutoProcessor.from_pretrained("neulab/Pangea-7B")
print(type(processor))

# <class 'transformers.models.qwen2.tokenization_qwen2_fast.Qwen2TokenizerFast'>
```

**Comment by yueqis** [comment]
Hi! We added example inference code under the predict folder! :)

**Comment by ahmedheakl** [comment]
Thank you so much @yueqis.
