### ISSUE TITLE
About multilingual pretraining dataset

### ISSUE THREAD

**Issue by yeppp27** [neulab/Pangea#2]
Hi! Thanks for your great work. Will the multi-language pre-training dataset (image caption) be made public?

**Comment by yueqis** [comment]
Hi! The multilingual training dataset PangeaIns is already public at [huggingface](https://huggingface.co/datasets/neulab/PangeaInstruct)! :)

**Comment by yeppp27** [comment]
Thanks a lot. But the file cultural/laion-multi-1M/part_00 on huggingface is not a compressed package. How can I decompress it? By the way, is it only the "cultural/laion-multi-1M" portion that contains a multilingual caption dataset? Looking forward to your kind response~

**Comment by yueqis** [comment]
Hi! 

I added some instructions on how to decompress files like part_00 on [huggingface](https://huggingface.co/datasets/neulab/PangeaInstruct). Basically, you would need to first combine the splitted tar files into one by `cat part_* > images.tar`, and then you could untar the file by `tar -xvf images.tar`

for captioning, "caption/STAIR-Captions" and "cultural/laion-multi-1M" contains multilingual caption data, while the other multilingual datasets are mostlly designed for more general purposes.

**Comment by yeppp27** [comment]
Thanks!
