### ISSUE TITLE
Request for GPU and Hardware Details for Pretraining and Fine-tuning with PangeaIns Dataset

### ISSUE THREAD

**Issue by nisshimura** [neulab/Pangea#4]
Hello,
I am interested in understanding the hardware setup used for training your model. Could you please provide details on the GPUs and other hardware specifications used during the following stages?

1. Pretraining / Fine-tuning with the PangeaIns dataset
What type of GPUs were used?
How many GPUs were utilized?
Were there any specific configurations or settings applied?

Your insights would be greatly appreciated as they will help me better understand the requirements and optimize my own setup.
Thank you!

**Comment by xiangyue9607** [comment]
Hi,

Thanks for the question. Both pre-training and fine-tuning were done using a single node with 8*H100s. 

Pre-training used the same dataset as Llava and took 4h to finish. 
Fine-tuning used PangeaIns and took 7-10 days to finish. We released the hyperparameters in our repo and paper.

Thanks!

Xiang
