### ISSUE TITLE
Why 39 languages?

### ISSUE THREAD

**Issue by conan1024hao** [neulab/Pangea#5]
Hi, thank you for your excellent paper! I have a question that how did you choose the 39 language candidtas? Do you have a specific criteria for this?

**Comment by yueqis** [comment]
Hi! We carefully selected these 39 languages based on the following considerations:

1. Comprehensive Coverage: We aimed to include languages from all continents, ensuring comprehensive language coverage.
2. Speaker Population: We aimed to include a balanced mix of widely spoken, moderately spoken, and less commonly spoken languages.
3. Training Data Availability: We prioritized languages with existing training data to facilitate comprehensive training.
