### ISSUE TITLE
CVQA size mismatch

### ISSUE THREAD

**Issue by jujeongho0** [neulab/Pangea#7]
Hi. Thank you for Great Work! :)

In the paper, the size of CVQA is 21k, while in Huggingface(https://huggingface.co/datasets/afaji/cvqa) it is 10K. As I understand it, the CVQA score table in the paper is based on a 21K dataset, and the CVQA score table in the current leaderboard(https://eval.ai/web/challenges/challenge-page/2305/overview) is based on a 10k dataset?

Thank you.

**Comment by yueqis** [comment]
Hi! We wrote in the paper that the size of CVQA is 21k because we tested both the original CVQA and the CVQA translated questions, which makes 20.8k instances in total.
